#!/bin/bash

__ScriptVersion="1.0.0"

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage ()
{
    echo "Usage :  $0 [options] [--]

    Options:
    -h|help             Display this message
    -v|version          Display script version
    -f|file <filename>  Specify file
    -m|message          Cat argument directly to file"

}    # ----------  end of function usage  ----------

#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------

filename="$HOME/.cache/viminput/input.txt"

#===  FUNCTION  ================================================================
#         NAME:  updateFileName
#  DESCRIPTION:  Updates the filename
#===============================================================================
function updateFileName() {
    if [ $# != 1 ]; then
        echo "You must specify the filename"
        exit 1
    elif [ $1 == 'vim' ]; then
        filename="$HOME/.cache/viminput/vim-input.txt"
    else
        filename="$1"
    fi
}


while getopts ":hvmf" opt
do
  case $opt in

    h|help     )  usage; exit 0   ;;

    v|version  )  echo "$0 -- Version $__ScriptVersion"; exit 0 ;;

    f|file     )  updateFileName ${!OPTIND}; OPTIND=OPTIND+1;;

    m|message  )  echo "${!OPTIND}" > $filename; OPTIND=OPTIND+1; exit 0 ;;

    * )  echo -e "\n  Option does not exist : $OPTARG\n"
          usage; exit 1   ;;

  esac    # --- end of case ---
done
shift $(($OPTIND-1))


$EDITOR "$filename"
