#!/usr/bin/env bash

$@ xorg xorg-xinit xfce4 plank cairo-dock dmenu compton # docky

cd /tmp/
git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git
cd WhiteSur-gtk-theme
./install.sh


cd /tmp/
git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git
cd WhiteSur-gtk-theme
./install.sh

cp ~/.themes/WhiteSur-dark/plank ~/.local/share/plank/themes/WhiteSur-dark
cp ~/.themes/WhiteSur-light/plank ~/.local/share/plank/themes/WhiteSur-light

